### ISSUE TITLE
QR code is partly covered.

### ISSUE THREAD

**Issue by quinreis** [dakhnod/Meshenger#25] opened 2019-07-02 14:42 UTC
The QR code is partly covered by the "share" icon, so it fails to scan with another phone. See screenshot![Screenshot_20190702-163944_Meshenger](https://user-images.githubusercontent.com/29644810/60521742-1169c180-9ce8-11e9-9ec9-95e3fc6faacd.jpg)
.

**Comment by iamvasuh** [comment] 2019-07-03 18:13
This issue has been fixed in this link: [QR-Code Presenter](https://github.com/meshenger-app/meshenger-android/commit/39a8734d118dc7e47e865bd2e7c92d034966b191)

**Comment by quinreis** [comment] 2019-07-06 10:57
I will try it out, but I am not sure how to put together the .apk file, as I had just downloaded it from F-droid.

**Comment by iamvasuh** [comment] 2019-07-06 12:19
I can send you a .apk file

**Comment by mwarning** [comment] 2019-08-17 23:13
@quinreis Can you check if this is still a problem? https://github.com/meshenger-app/meshenger-android/releases/tag/v2.0.0 - thanks.

**Comment by ghost** [comment] 2019-08-28 18:42
The issue is resolved. :-)

**Closed by ghost** 2019-08-28 18:42 UTC
